const reveal_types = [
    "None", 
    "Fade", 
    "Flip", 
    "Rotate",
    "Zoom",
    "Bounce",
    "Slide",
    "Roll",
    "LightSpeed",
    "Jump",
    "Flash", 
    "HeadShake", 
    "Jello", 
    "Pulse", 
    "RubberBand", 
    "Shake", 
    "Spin", 
    "Swing", 
    "Tada", 
    "Wobble", 
    "Reveal", 
]
export { reveal_types }